from __future__ import annotations

# From 'Gemini Project - Data Specifications' (Star Systems list)
STAR_SYSTEMS = [
  "Andromeda",
  "Antlia",
  "Apus",
  "Aquarius",
  "Aquila",
  "Ara",
  "Aries",
  "Auriga",
  "Boötes",
  "Caelum",
  "Camelopardalis",
  "Cancer",
  "CanesVenatici",
  "CanisMajor",
  "CanisMinor",
  "Capricornus",
  "Carina",
  "Cassiopeia",
  "Centaurus",
  "Cepheus",
  "Cetus",
  "Chamaeleon",
  "Circinus",
  "Columba",
  "ComaBerenices",
  "CoronaAustralis",
  "CoronaBorealis",
  "Corvus",
  "Crater",
  "Crux",
  "Cygnus",
  "Delphinus",
  "Dorado",
  "Draco",
  "Equuleus",
  "Eridanus",
  "Fornax",
  "Gemini",
  "Grus",
  "Hercules",
  "Horologium",
  "Hydra",
  "Hydrus",
  "Indus",
  "Lacerta",
  "Leo",
  "LeoMinor",
  "Lepus",
  "Libra",
  "Lupus",
  "Lynx",
  "Lyra",
  "Mensa",
  "Microscopium",
  "Monoceros",
  "Musca",
  "Norma",
  "Octans",
  "Ophiuchus",
  "Orion",
  "Pavo",
  "Pegasus",
  "Perseus",
  "Phoenix",
  "Pictor",
  "Pisces",
  "PiscisAustrinus",
  "Puppis",
  "Pyxis",
  "Reticulum",
  "Sagitta",
  "Sagittarius",
  "Scorpius",
  "Sculptor",
  "Scutum",
  "Serpens",
  "Sextans",
  "Taurus",
  "Telescopium",
  "Triangulum",
  "TriangulumAustrale",
  "Tucana",
  "UrsaMajor",
  "UrsaMinor",
  "Vela",
  "Virgo",
  "Volans",
  "Vulpecula"
]

TELESCOPE_LOCATIONS = ["Hawaii", "Chile"]

FILE_TYPES = ["PNG", "JPEG", "RAW"]
FILE_QUALITIES = ["Low", "Fine"]

IMAGE_MODES = ["B&W", "Color"]

CALIBRATION_UNITS = ["Argon", "CuAr", "ThAr", "Xenon"]
LIGHT_TYPES = ["CerroPachonSkyEmission", "MaunaKeaSkyEmission"]
FOLD_MIRROR_TYPES = ["CASSEGRAIN_FOCUS", "REFLECTIVE_CONVERGING_BEAM"]
DIRECTIONS = ["North", "East", "West", "South"]
